const DEFAULT_SKIP = 0
const DEFAULT_LIMIT = 10
const DEFAULT_SORT = '-_id'

const MONGO_CONSTANTS = {
  DEFAULT_SKIP,
  DEFAULT_LIMIT,
  DEFAULT_SORT
}

export default MONGO_CONSTANTS
export {
  DEFAULT_SKIP,
  DEFAULT_LIMIT,
  DEFAULT_SORT
}
